#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

const dataDir = path.join(__dirname, 'data');
const outputFile = path.join(__dirname, 'data', 'gameData.js');

console.log('Generating gameData.js from CSV files...');

// Simple CSV parser
function parseCSV(content) {
    const lines = content.trim().split('\n');
    if (lines.length === 0) return [];

    const headers = parseCSVLine(lines[0]);
    const rows = [];

    for (let i = 1; i < lines.length; i++) {
        const line = lines[i].trim();
        if (!line) continue;

        const values = parseCSVLine(line);
        const row = {};
        for (let j = 0; j < headers.length; j++) {
            row[headers[j]] = values[j] || '';
        }
        rows.push(row);
    }

    return rows;
}

function parseCSVLine(line) {
    const result = [];
    let current = '';
    let insideQuotes = false;

    for (let i = 0; i < line.length; i++) {
        const char = line[i];
        const nextChar = line[i + 1];

        if (char === '"') {
            if (insideQuotes && nextChar === '"') {
                current += '"';
                i++;
            } else {
                insideQuotes = !insideQuotes;
            }
        } else if (char === ',' && !insideQuotes) {
            result.push(current);
            current = '';
        } else {
            current += char;
        }
    }

    result.push(current);
    return result;
}

function readCSV(filePath) {
    try {
        if (!fs.existsSync(filePath)) {
            return [];
        }
        const content = fs.readFileSync(filePath, 'utf-8');
        return parseCSV(content);
    } catch (error) {
        console.error(`Error reading ${filePath}:`, error.message);
        return [];
    }
}

function parseJson(jsonString) {
    if (!jsonString) return null;
    try {
        return JSON.parse(jsonString);
    } catch (e) {
        return null;
    }
}

// Read existing gameData.js to preserve other data
let existingData = {};
try {
    const currentContent = fs.readFileSync(outputFile, 'utf-8');
    const match = currentContent.match(/const GAME_DATA = ({[\s\S]*});/);
    if (match) {
        existingData = eval('(' + match[1] + ')');
    }
} catch (e) {
    console.warn('Could not read existing gameData.js, will create new one');
}

// Initialize collections - preserve existing data, update trading-related
const gameData = {
    ...existingData,
    tradingRegions: [],
    tradingRegionUpgrades: []
};

// Process tradingRegion.csv
const tradingRegionPath = path.join(dataDir, 'trading', 'tradingRegion.csv');
const regions = readCSV(tradingRegionPath);
for (const region of regions) {
    if (region.id) {
        gameData.tradingRegions.push({
            id: region.id,
            name: region.name
        });
    }
}
console.log(`✓ Loaded ${gameData.tradingRegions.length} trading regions from tradingRegion.csv`);

// Process tradingRegionUpgrade.csv
const tradingRegionUpgradePath = path.join(dataDir, 'trading', 'tradingRegionUpgrade.csv');
const upgrades = readCSV(tradingRegionUpgradePath);
for (const upgrade of upgrades) {
    if (upgrade.id) {
        const upgradeData = {
            id: upgrade.id,
            level: parseInt(upgrade.level) || 1,
            exp: parseInt(upgrade.exp) || 1000,
            orderList: parseJson(upgrade.orderList) || []
        };
        gameData.tradingRegionUpgrades.push(upgradeData);
    }
}
console.log(`✓ Loaded ${gameData.tradingRegionUpgrades.length} trading region upgrades from tradingRegionUpgrade.csv`);

// Generate the gameData.js file
const output = `/**
 * Game Data - Embedded data files
 * AUTO-GENERATED by build_game_data.js - Do not edit manually
 * This file contains all game data in JavaScript format
 * Run 'node build_game_data.js' or 'BuildData.bat' to regenerate after updating CSV files
 */

const GAME_DATA = ${JSON.stringify(gameData, null, 4)};
`;

fs.writeFileSync(outputFile, output);
console.log(`✓ Generated ${outputFile}`);
console.log('Build complete!');
